### ISSUE TITLE
Taxonomy tag prints two sets of terms

### ISSUE THREAD

**Issue by Bwata** [Stillat/relationships#13]
I have a collection that has a related taxonomy. I was using this add-on to make the bi-directional connection between the two. Mostly so I can sort the collection entries in the taxonomy. I was then printing out the taxonomy terms with the [taxonomy tag](https://statamic.dev/tags/taxonomy) and it printed out the normal terms with the `{{title}}` being the normal title case name of the term. and then it prints additional terms only when this add-on is installed. I can tell because the `{{title}}` is all snake cased of the taxonomy name and term. Example: if the taxonomy is "Building Type" and the term is "Gas Station", then the output would be `building_typegas_station`. Is there a work around you are aware of? I really want to use this add on so any help would be appreciated. Thanks.

**Comment by JohnathonKoster** [comment]
Hi there!

Would you be able to create a simple sample repository that recreates this issue?

**Comment by Bwata** [comment]
https://github.com/Bwata/Statamic-Relationships-Add-on-Example

**Comment by JohnathonKoster** [comment]
Thanks for the example. I've taken a look, and found the term you wish to remove is listed as an actual term, which would make it appear in the tag output:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/5232890/221922309-9e273dfb-932b-411c-87dd-6fd499314781.png">

The following relationship also does not match the handles inside the buildings blueprint:

```php
<?php

Relate::manyToMany(
    'term:building_types.buildings',
    'buildings.building_type'
);
```

<img width="845" alt="image" src="https://user-images.githubusercontent.com/5232890/221922641-94c2d18f-a92e-4122-ad67-1685661209ed.png">

After removing the incorrect term, updating the relationship to match the handles:

```php
<?php

Relate::manyToMany(
    'term:building_types.buildings',
    'buildings.building_types'
);
```

And then running:

```bash
php please relate:fill
```

I have been unable to reproduce this

**Comment by JohnathonKoster** [comment]
That I'm not sure on - I wasn't able to reproduce creating that term even with the typo.
