### ISSUE TITLE
Support for Statamic 4 ? 

### ISSUE THREAD

**Issue by laradevca** [Stillat/relationships#17]
Any plan on this package getting support for Statamic 4 ? Anything we can do to help ?

**Comment by JohnathonKoster** [comment]
Working on it 😅

**Comment by laradevca** [comment]
Awesome ! Thank you for you work sir <3

**Comment by JohnathonKoster** [comment]
Just tagged a `2.0.0` that updates the dependencies/tests for Statamic 4 🙂
