### ISSUE TITLE
Allow set notation for one to many relationship

### ISSUE THREAD

**Issue by mikemartin** [Stillat/relationships#24]
Hey mate,
Is it possible to enable set notation for one to many relationships? It doesn't appear to be working. Here are my relations and the relate fill output:

```
Relate::oneToMany(
    'entry:{pens,markers,accessories}.refill',
    'refills.products'
);

Relate::oneToMany(
    'reviews.product',
    'entry:{pens,markers,accessories,refills}.reviews'
);
```

Output:
```
❯ php please relate:fill
Updating relationships. This may take a while if you have a lot of entries.

Updating relationship: (1-*) [refills.products {pens,markers,accessories}.refill]...
Updating relationship: (1-*) [refills.products {pens,markers,accessories}.refill]... done!
Updating relationship: (*-1) [reviews.product {pens,markers,accessories,refills}.reviews]...
Updating relationship: (*-1) [reviews.product {pens,markers,accessories,refills}.reviews]... done!
```

**Comment by JohnathonKoster** [comment]
This is now available as a new feature in v2.1.0 (S4) 🙂

Set notation has been added to all relationship types (oneToOne, oneToMany, manyToOne, manyToMany)

**Comment by mikemartin** [comment]
@JohnathonKoster Thanks, but it still doesn't seem to be working after the update. Relate list is listing one relationships with the set notation and not listing all the relationships.

**Comment by JohnathonKoster** [comment]
@mikemartin  I'll get you a new version tagged here soon 

🤦‍♂️🤦‍♂️I didn't merge the branch.

**Comment by JohnathonKoster** [comment]
@mikemartin  Just tagged 2.1.1 with the actual changes. Sorry about that 🐸

**Comment by mikemartin** [comment]
Awesome. Thank you!
