### ISSUE TITLE
__clone method called on non-object

### ISSUE THREAD

**Issue by markusreis-yd** [Stillat/relationships#28]
Hey there,

I am not quite sure if I am right, but shouldn't [this line](https://github.com/Stillat/relationships/blob/main/src/Listeners/BaseListener.php#L12) check, if an ID exists / the model property `is_null`? You already do the isUpdating check in the respective SavingListeners (eg. [EntrySavingListener](https://github.com/Stillat/relationships/blob/main/src/Listeners/EntrySavingListener.php#L40)) but then you try to clone it anyways in the DB-Check Method.

When I create a new entry within my collection, I get the exception `[2023-11-20 09:23:33] local.ERROR: __clone method called on non-object {"userId":1,"exception":"[object] (Error(code: 0): __clone method called on non-object at /var/www/html/vendor/stillat/relationships/src/Listeners/BaseListener.php:15)`

When I update an existing entry, everything is fine.

**Comment by JohnathonKoster** [comment]
I'll try to take a look sometime this week before some holidays here

If you are able to submit a PR in the meantime that I can review, I would really appreciate that. Thank you!

**Comment by JohnathonKoster** [comment]
Thank you! I will review this evening my time!
