### ISSUE TITLE
Sync issues with withEvents(true) and manyToMany relationships

### ISSUE THREAD

**Issue by MedRochon** [Stillat/relationships#32]
Hi, I got an issue when using a manyToMany with withEvents(true) relation when I link Item1 to Case1 & Case2 (both at the same time). The link is good in Item1, I can see both Case1 & Case2, but the opposite link isn't good, only Case1 is linked to Item1 and not Case2. If I remove withEvents(true) then, everything works fine, all links are created !

**Comment by JohnathonKoster** [comment]
It's quite possible that the additional events are causing data to be overwritten currently. Can I ask the use case for needing the events triggered during the sync process (just curious)?

**Comment by MedRochon** [comment]
We are using it for the Git Automation, to push both files to git !

**Comment by JohnathonKoster** [comment]
I see. I'll review options to fix this, but it may take some time to resolve, and cannot guarantee any timelines.

**Comment by MedRochonTolle** [comment]
Hi, any updates ?

**Comment by JohnathonKoster** [comment]
Not yet, unfortunately. I've been quite busy, but will try and find time soon to take a look!

**Comment by marcorieser** [comment]
Running into issues with oneToMany. Will try to create a test repo and a specific issue tomorrow. Thanks John for your awesome work!

**Comment by JohnathonKoster** [comment]
Resolved with 2.1.5
