### ISSUE TITLE
Error when working with the database

### ISSUE THREAD

**Issue by Dragon001-github** [Stillat/relationships#34]
Hello, we have encountered a problem while working with a database.

We have created two entities and linked them together as specified in the instructions.

When adding, everything works fine, but when we delete an item from either entity, it remains in the other one.

Looking at the code,we found that when we pull out the old data:

![image](https://github.com/Stillat/relationships/assets/31285414/b76fbad4-fcee-496c-8c30-2c0eac0c940e)

The function inside that tries to get the data out of the model tries to find it at the same level when the data in the standard model lies in data.

![image](https://github.com/Stillat/relationships/assets/31285414/946c7d95-c8b6-40e6-b5d4-558977f583bb)
![image](https://github.com/Stillat/relationships/assets/31285414/bf72ef9b-ce6a-4470-8f82-4777abfb8021)

Is this an actual problem or is this us not handling the model correctly?

We are using the standard driver https://github.com/statamic/eloquent-driver

**Comment by JohnathonKoster** [comment]
Would you be able to put together a test repo that contains your specific setup that I could look at? That would help to answer your question better. Thanks!

**Comment by Dragon001-github** [comment]
Hello, I apologize for the long reply.

It's actually quite simple.

I installed pure Statamic, configured the Eloquent driver to store Entry in the database.

2 entities were created through Statamic admin.
2 random fields were merged together. For us it was: Exhibits and Champions.

Communication via Provider was set up.

` Relate::manyToMany(
            'exhibits.champions',
            'champions.exhibits'
        )->allowDelete(false);`

After that when saving everything works fine, when deleting it does not work.

**Comment by JohnathonKoster** [comment]
When you say deleting does not work, are you saying deleting itself does not work, or that nothing happens with the relationships?

**Comment by Dragon001-github** [comment]
When you delete a champion from an exhibit, for example, the exhibit remains in the champion.

**Comment by JohnathonKoster** [comment]
@GertTimmerman Thanks for the comment! If you have time, would it be possible to put together a small repo that replicates this using the Eloquent driver and SQLite? This really helps to accelerate my side of things once I get into it

**Comment by GertTimmerman** [comment]
> @GertTimmerman Thanks for the comment! If you have time, would it be possible to put together a small repo that replicates this using the Eloquent driver and SQLite? This really helps to accelerate my side of things once I get into it

I have created it here: https://github.com/GertTimmerman/statamic-entry-relationshop-db

When you change the author of a book, all the relations will mess up

**Comment by JohnathonKoster** [comment]
Thanks for the repo! I'll take a look this week and get something going for this

**Comment by JohnathonKoster** [comment]
Improved DB support with 2.2.1
