### ISSUE TITLE
Sync issues with `oneToMany`

### ISSUE THREAD

**Issue by marcorieser** [Stillat/relationships#35]
## Issue
I have some weird sync problems when using `oneToMany()`.

Personally I do not need events to be triggering but since there are issues (https://github.com/Stillat/relationships/issues/32) when they are enabled, I tested my cases with them enabled too.

## Reproduction
- Clone this repo: https://github.com/marcorieser/statamic-relationships
  - It contains two collections (Books and Authors)
  - A book can have only one author
  - Authors can have many books
  - Events are disabled (`withEvents(false)`)
  - Relationship is set up in `AppServiceProvider::boot()`
- Go through the test cases listed below

## Test Cases (`withEvents(false)`)
> [!CAUTION]
> Make sure to reset the changes in content between the cases.
<table>
<tr>
<th>Case</th>
<th>Expected</th>
<th>Actual</th>
<th>Passes</th>
</tr>
<tr>
<td>In a book entry, remove the author and save</td>
<td>

- Author gets removed from book entry
- Book gets removed from author entry

</td>
<td>

- Author gets removed from book entry
- Book gets removed from author entry

</td>
<td>✅</td>
</tr>
<tr>
<td>In an author entry, remove a book and save</td>
<td>

- Book gets removed from author entry
- Author gets removed from book entry

</td>
<td>

- Book gets removed from author entry
- Author gets removed from book entry

</td>
<td>✅</td>
</tr>
<tr>
<td>In an author entry, assign a book already assigned to another author</td>
<td>

- Book gets added to the saving author entry
- Book gets removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>

- Book gets added to the saving author entry
- Book does **NOT** get removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>❌</td>
</tr>
<tr>
<td>In a book entry, assign another author</td>
<td>

- Book gets added to the new author entry
- Book gets removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>

- Book gets added to the new author entry
- Book gets removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>✅</td>
</tr>
</table>

## Test Cases (`withEvents(true)`)
> [!CAUTION]
> Make sure to reset the changes in content between the cases.
<table>
<tr>
<th>Case</th>
<th>Expected</th>
<th>Actual</th>
<th>Passes</th>
</tr>
<tr>
<td>In a book entry, remove the author and save</td>
<td>

- Author gets removed from book entry
- Book gets removed from author entry

</td>
<td>

- Author gets removed from book entry
- Book gets removed from author entry

</td>
<td>✅</td>
</tr>
<tr>
<td>In an author entry, remove a book and save</td>
<td>

- Book gets removed from author entry
- Author gets removed from book entry

</td>
<td>

- **All** related Books get removed from author entry
- Author gets removed from **some** (but not all) previous related book entries

</td>
<td>❌</td>
</tr>
<tr>
<td>In an author entry, assign a book already assigned to another author</td>
<td>

- Book gets added to the saving author entry
- Book gets removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>

- Book gets added to the saving author entry
- Book gets removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>✅</td>
</tr>
<tr>
<td>In a book entry, assign another author</td>
<td>

- Book gets added to the new author entry
- Book gets removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>

- Book gets added to the new author entry
- Book does **NOT** get removed from the previous author entry
- Author gets changed in the book entry

</td>
<td>❌</td>
</tr>
</table>

**Comment by JohnathonKoster** [comment]
Thank you very much for this!

**Comment by marcorieser** [comment]
Glad you found the issue. Thank you so much.

**Comment by JohnathonKoster** [comment]
Another edge case cropped up that is proving to be challenging. Will keep you updated 👍

**Comment by JohnathonKoster** [comment]
Alright, I've got all but this one working now "In an author entry, assign a book already assigned to another author" (withEvents = false). I'll do some thinking on if that can be reasonably supported without cascading events.

I'm going to sit on this one overnight and work on some test coverage before pushing it out, though

**Comment by JohnathonKoster** [comment]
As soon as I walked away I thought of a solution. All of your scenarios will now work, regardless of the `withEvents` setting, with expanded test coverage. Should be good to go as of 2.1.5

Thanks again for putting together such a great sample repo!

**Comment by marcorieser** [comment]
Just gave it a shot and everything works like a charm. Tried to be a bit mean by mix and match cases from above. Everything perfect. Thank you!
