### ISSUE TITLE
2.1.5 relate:fill command removes all relationships (I only have oneToMany)

### ISSUE THREAD

**Issue by isaackearl** [Stillat/relationships#37]
Hello,

We have a fairly simple setup in our project.  Everything works great on version 2.1.4, after upgrading to the latest version, whenever we run the relate:fill command, it simply removes all the relationships.  The only thing we are doing is vanilla oneToMany relationships.  For now I've downgraded to 2.1.4 as that version continues to work great.  On 2.1.5 there is no other indication of issue.  The relate:list command runs and lists all the commands correctly.

<img width="1399" alt="image" src="https://github.com/Stillat/relationships/assets/9354830/648bc86c-cfbd-40ab-8313-4d4f1db8d8c9">

<img width="480" alt="image" src="https://github.com/Stillat/relationships/assets/9354830/a3e12e2e-b8c1-403e-9a1d-9bf033f206b2">

On 2.1.5 when I run the command it appears to work great in the terminal, but the result is all the relationships are gone
<img width="1581" alt="image" src="https://github.com/Stillat/relationships/assets/9354830/889f028f-194d-4663-990a-1442e8442be3">

**Comment by JohnathonKoster** [comment]
Would you be able to setup an example repository that exhibits this behavior? That would help to track this down

**Comment by isaackearl** [comment]
> Would you be able to setup an example repository that exhibits this behavior? That would help to track this down

I went ahead and made a VERY simple repository that exhibits the same behavior.  The relationship gets cleared from 1 side. 

INSTRUCTIONS:

1. checkout: https://github.com/vicam-consulting/relations-test
2. composer install
3. go and look at the control panel and test the relationship between categories and products, you'll see that everything is working great (when you attach one, it will be attached on the other side etc)
4. now run php please relate:fill, and take a look at git and notice that all of the products have been removed from the category.  In other words the "automatic inverse" relationship is all cleared out.

**Comment by JohnathonKoster** [comment]
Thank you very much for this! I'll take a look this week and let you know what I find out

**Comment by JohnathonKoster** [comment]
A fix for this is available in 2.1.6
