### ISSUE TITLE
Revisions seem not to be compatible with relationships

### ISSUE THREAD

**Issue by j3ll3yfi5h** [Stillat/relationships#9]
Hi @JohnathonKoster!

Thank you very much for your Statamic work and this awesome addon!

Just came across a bug: revisions and relationships seem not to be compatible.

I'm not sure if it is a good decision to use them both in parallel anyway, but my use case seems from my perspective not so wrong:
- little newspaper
- editions
- articles (with revisions)
- one editions has many articles

Any thoughts or solutions?

**Comment by j3ll3yfi5h** [comment]
Hm...found out, that I used the wrong type for the relationship.🤦🏼‍♂️

But what would be the correct behavior with a new relationship? A new revision?

**Comment by JohnathonKoster** [comment]
My initial feeling would be that it should create a new revision if both sides used revisions. Will need to experiment 🙂
